# Generated by Django 2.0.3 on 2018-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_say',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat_time', models.TextField()),
                ('back_date', models.TextField()),
                ('drug_style', models.TextField()),
                ('not_eat', models.TextField()),
                ('side_effect', models.TextField()),
                ('recorder', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doctor_say',
            },
        ),
        migrations.CreateModel(
            name='family_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('identity_card', models.TextField()),
                ('health_card', models.TextField()),
                ('health_pwd', models.TextField()),
                ('name', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'family_relationship',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_card', models.TextField()),
                ('health_card', models.TextField()),
                ('health_pwd', models.TextField()),
                ('asus_account', models.TextField()),
                ('asus_pwd', models.TextField()),
                ('token', models.TextField()),
                ('name', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
