# Generated by Django 2.0.3 on 2018-06-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_url', models.TextField()),
                ('food_eff', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
    ]
