# Generated by Django 2.0.3 on 2018-06-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='food_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
