# Generated by Django 2.0.3 on 2018-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_disease_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_say',
            name='disease_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_say',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_say',
            name='record_time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
