# Generated by Django 2.0.3 on 2018-07-12 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180613_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField()),
                ('disease_food', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'disease_food',
            },
        ),
        migrations.CreateModel(
            name='health_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appellation', models.TextField()),
                ('identity', models.TextField()),
                ('blood_pressure', models.TextField()),
                ('blood_sugar', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_info',
            },
        ),
        migrations.CreateModel(
            name='last_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'last_news',
            },
        ),
        migrations.CreateModel(
            name='push_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('token', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'push_info',
            },
        ),
        migrations.CreateModel(
            name='token_disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('disease', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'token_disease',
            },
        ),
        migrations.AddField(
            model_name='doctor_say',
            name='identity',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
